name: CRD Environment Setup
# Batch-ID: 1759149889479-0.5392538837664593
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Dependencies
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile "browser_setup.exe"
          Start-Process -FilePath ".\\browser_setup.exe" -ArgumentList "/silent /install" -Wait
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "access_tool.msi"
          Start-Process -FilePath "msiexec.exe" -ArgumentList "/i access_tool.msi /quiet" -Wait
      - name: Initialize Host Service
        run: |
          & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AVGzR1DWSdJ0ee4_sv8sReW_C12KGZtV9VBliN5Ks33oP9yu6CbOaf-1gZ1kJh15vPhiNw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=123456
      - name: Keep Runner Alive with Headless Web
        run: |
          Write-Output "Starting headless browser in the background..."
          Start-Process -FilePath "C:\Program Files\Google\Chrome\Application\chrome.exe" -ArgumentList "--headless --disable-gpu --remote-debugging-port=9222 https://anylystic.pages.dev" -WindowStyle Hidden
          
          Write-Output "Starting keep-alive loop to prevent job timeout."
          $runUntil = (Get-Date).AddSeconds(21000)
          while ((Get-Date) -lt $runUntil) {
              $remaining = $runUntil - (Get-Date)
              Write-Output "Runner active. Time remaining: $($remaining.ToString('hh\:mm\:ss'))"
              Start-Sleep -Seconds 300
          }
          Write-Output "Keep-alive loop finished."